name: Sample Shell Script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      run: |
      
             #chmod +x "${GITHUB_WORKSPACE}/../test.sh"
             echo ${GITHUB_WORKSPACE}
             chmod +x "./test.sh"
             ${GITHUB_WORKSPACE}/test.sh
             ./test.sh
          #./test.sh
          
    - name: get the pushed tag
      id: pushed-tag
      run: |
          echo "TAG_NAME=${{  github.ref_name }}" >> $GITHUB_OUTPUT
    - run: git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"
    - name: Checkout the pushed tag
      run: |
          tag_name="${{ steps.pushed-tag.outputs.TAG_NAME }}"
          git fetch --all --tags
          git checkout "tags/${tag_name}" -b "merge/development/${tag_name}"


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
      #uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
